
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    name: minio
    app: minio
spec:
  selector:
    name: minio
  ports:
  - name: http
    port: 9000
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: minio-0
  labels:
    name: minio
    app: minio
spec:
  selector:
    name: minio-0
  ports:
  - name: http
    port: 9000
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: minio-1
  labels:
    name: minio
    app: minio
spec:
  selector:
    name: minio-1
  ports:
  - name: http
    port: 9000
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: minio-2
  labels:
    name: minio
    app: minio
spec:
  selector:
    name: minio-2
  ports:
  - name: http
    port: 9000
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: minio-3
  labels:
    name: minio
    app: minio
spec:
  selector:
    name: minio-3
  ports:
  - name: http
    port: 9000
    protocol: TCP
