apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: minio
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        command: ["/usr/bin/minio"]
        args:
            - server
            - "localhost:9000/data"
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: data-store
          mountPath: /export
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
      volumes:
      - name: data-store
        emptyDir: {}
